import os
from PIL import Image

# Path to the source image generated by the AI
SOURCE_IMAGE = r"C:\Users\lanxy\.gemini\antigravity\brain\1edcfe83-e4a5-44d3-b80f-410df5995441\favicon_design_1773129066983.png"
# Destination directory
PUBLIC_DIR = r"h:\git\zhongwei\hatify\public"

def create_favicons():
    if not os.path.exists(SOURCE_IMAGE):
        print(f"Error: Source image not found at {SOURCE_IMAGE}")
        return

    img = Image.open(SOURCE_IMAGE)
    
    # 1. favicon.ico (16, 32, 48)
    ico_path = os.path.join(PUBLIC_DIR, "favicon.ico")
    img.save(ico_path, format='ICO', sizes=[(16, 16), (32, 32), (48, 48)])
    print(f"Created {ico_path}")

    # 2. favicon-32x32.png
    img_32 = img.resize((32, 32), Image.Resampling.LANCZOS)
    img_32.save(os.path.join(PUBLIC_DIR, "favicon-32x32.png"))
    print("Created favicon-32x32.png")

    # 3. favicon-16x16.png
    img_16 = img.resize((16, 16), Image.Resampling.LANCZOS)
    img_16.save(os.path.join(PUBLIC_DIR, "favicon-16x16.png"))
    print("Created favicon-16x16.png")

    # 4. apple-touch-icon.png (180x180)
    img_180 = img.resize((180, 180), Image.Resampling.LANCZOS)
    img_180.save(os.path.join(PUBLIC_DIR, "apple-touch-icon.png"))
    print("Created apple-touch-icon.png")

    # 5. android-chrome-192x192.png
    img_192 = img.resize((192, 192), Image.Resampling.LANCZOS)
    img_192.save(os.path.join(PUBLIC_DIR, "android-chrome-192x192.png"))
    print("Created android-chrome-192x192.png")

    # 6. android-chrome-512x512.png
    img_512 = img.resize((512, 512), Image.Resampling.LANCZOS)
    img_512.save(os.path.join(PUBLIC_DIR, "android-chrome-512x512.png"))
    print("Created android-chrome-512x512.png")

if __name__ == "__main__":
    create_favicons()
